stages:
  - push_to_external_repo

push_to_external_repo:
  stage: push_to_external_repo
  script:
    - git remote add external_repo https://dcarrascoh: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github.com/dcarrascoh/syncrepos.git
    - git fetch
    - git remote -v
    - git checkout origin/main
    - git push external_repo main:main