sync-with-github:
  before_script:
    - git config user.name "${GITLAB_USER_NAME}"
    - git config user.email "${GITLAB_USER_EMAIL}"
  script:
    - git remote add github https://github.com/dcarrascoh/syncrepos.git
    - git checkout main
    - git pull origin main
    - git pull github master
    - git status
    - git push https://root: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@github.com/dcarrascoh/syncrepos.git HEAD:main