stages:
  - deploy

deploy_to_AEM:
  stage: deploy
  script:
    - echo "Deploying to AEM Cloud - '$CI_DEPLOY_PASSWORD' - '$CI_JOB_STAGE'" # Agrega comandos para sincronizar tu código con AEM Cloud aquí

  only:
    - main # Este job solo se ejecutará cuando se haga un push a la rama 'master'
