stages:
  - sync

sync:
  stage: sync
  script:
    - git remote add upstream https://dcarrascoh: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@github.com/dcarrascoh/syncrepos.git
    - git remote -v
    - git push upstream main